# https://taskfile.dev

version: '3'

vars:
  PB_ZIP: https://github.com/pocketbase/pocketbase/releases/download/v0.36.0/pocketbase_0.36.0_windows_amd64.zip

tasks:
  default:
    cmds:
      - task: run-pb
    silent: true

  run-pb:
    deps: [ download-pb ]
    cmds:
      - cmd /C pocketbase.exe superuser upsert admin@test.com password
      - cmd /C pocketbase.exe superuser upsert northburns@gmail.com password
      - cmd /C pocketbase.exe serve --http 127.0.0.1:8090

  download-pb:
    status:
      - test -f pocketbase.exe
    cmds:
      - curl -L {{.PB_ZIP}} -o pb.zip
      - defer: rm pb.zip
      - tar -xf pb.zip pocketbase.exe
